title: Pentest reports
description: >- # this means to ignore newlines until "baseurl:"
  Curated list of pentest reports from various security companies and individuals.
  Great content to learn about penetration testing methodologies and techniques.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pentestreports.com" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "favicon.ico"
twitter:
  username: reconmap
port: 4001
safe: true

whitelist:
  - jekyll-redirect-from

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

google_analytics: G-2K28WLDQ4M

collections:
  companies:
    output: true
    permalink: /company/:name
  videos:
    output: true
    permalink: /video/:name
  interviews:
    output: true
    permalink: /interview/:name

defaults:
  - scope:
      path: ""
    values:
      hero_height: is-small
  - scope:
      path: ""
      type: "companies"
    values:
      layout: company
  - scope:
      path: ""
      type: "videos"
    values:
      layout: video
  - scope:
      path: ""
      type: "interviews"
    values:
      layout: interview

footer_menu: footer

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile
